# Generated by Django 4.2.4 on 2023-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersShop', '0006_order_product_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_to_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='День рождения', max_length=250, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
